# This test job is separated out into its own workflow to be able to obtain a separate badge for it
name: CI-devtest

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main
  schedule:
    # run every Monday at 5am UTC
    - cron: '0 5 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: dev dependencies with all dependencies with coverage
            os: ubuntu-latest
            python: '3.12'
            toxenv: py312-test-alldeps-devdeps-cov
            toxargs: -v

          - name: Python 3.13
            os: ubuntu-latest
            python: '3.13-dev'
            toxenv: py313-test
            toxargs: -v

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: contains(matrix.toxenv,'-cov')
      uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574  # v5.4.0
      with:
        file: ./coverage.xml
